# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
cache: packages
before_install:
- Rscript -e 'if (!require("devtools")) install.packages("devtools", repos = "https://cran.rstudio.org")'
install:
- Rscript -e 'if (!require("devtools")) install.packages("devtools", repos = "https://cran.rstudio.org")'
script:
- Rscript 01_user_lib.R
- Rscript 02_r_packages.R
